In [2]:
import sys
sys.path.append('../src')
from utils.graph_utils import *
import numpy as np
import pandas as pd

In [3]:
graphs = get_all_sentiment_video_graphs()

In [7]:
x = [(g['category'], np.mean([score for score in g.vs['score'] if score is not None and not np.isnan(score)])) for g in graphs]
df = pd.DataFrame(x, columns=['category', 'mean_score'])

In [9]:
df.sort_values(by='mean_score', ascending=False)

           category  mean_score
29  Shared interest    0.246480
7     Entertainment    0.245850
13    Entertainment    0.229746
19  Shared interest    0.226241
20  Shared interest    0.222309
5   Shared interest    0.219991
32    Entertainment    0.190129
2     Entertainment    0.187453
8         Political    0.176211
26    Entertainment    0.170472
31    Entertainment    0.166770
24  Shared interest    0.157843
11    Entertainment    0.151981
14  Shared interest    0.151782
6     Entertainment    0.146783
1   Shared interest    0.143998
22  Shared interest    0.134467
17  Shared interest    0.134092
21    Entertainment    0.130219
35    Entertainment    0.121172
33    Entertainment    0.083794
10    Entertainment    0.078334
25  Shared interest    0.076277
23        Political    0.068574
30        Political    0.064419
9     Entertainment    0.062105
28        Political    0.053358
12        Political    0.046904
4         Political    0.043155
15        Political    0.024971
18        Political    0.019942
34        Political    0.006052
27    Entertainment   -0.002094
3         Political   -0.006736
0         Political   -0.020694
16        Political   -0.105863

In [10]:
df.groupby('category').mean_score.mean()

category
Entertainment      0.140194
Political          0.030858
Shared interest    0.171348
Name: mean_score, dtype: float64